on:
  push:
    branches: [AC-6]
    
name: Get Github Release Data
jobs:
  latest-version:
    name: Get Latest Release
    runs-on: ubuntu-latest
    environment: stage   #For Environment
    steps:
      - uses: actions/checkout@master
      - name: Get Latest Release
        id: latest_version
        uses: abatilo/release-info-action@v1.3.0
        with:
          owner: amitbind13
          repo: jira-github-deployment
      - name: Example of consumption of the output
        run: |
          owner="amitbind13"
          repo="jira-github-deployment"
          release_json=$(curl https://api.github.com/repos/$owner/$repo/releases)
          Release_tag=$(echo "$release_json" | jq -r '.[0].tag_name')
          Release_name=$(echo "$release_json" | jq -r '.[0].name')
          
       


         
          echo "Release_name: Latest Release Tag Name is : $Release_name"
          
         

          
          echo ::set-output name=Release_tag::"$Release_tag"
          echo ::set-output name=Release_name::"$Release_name"
          

# Code Optimization done.
